# Exported from Render on 2025-05-23T10:06:04Z
services:
- type: web
  name: InsightGrid
  runtime: python
  repo: https://github.com/SakshamDev2005/InsightGrid
  plan: free
  region: singapore
  buildCommand: pip install -r myproject/requirements.txt
  startCommand: gunicorn myproject.wsgi
  autoDeployTrigger: commit
version: "1"
